name: Build Jekyll & Deploy to HuggingFace

on:
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler: default
          bundler-cache: true

      - name: Install bundle
        run: |
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install HF client
        run: pip install --upgrade huggingface_hub

      - name: Deploy _site to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
        run: python .github/scripts/deploy_to_hf.py
